#!/bin/bash


# Check if amulet is installed before adding repository and updating apt-get.
dpkg -s amulet > /dev/null
if [ $? -ne 0 ]; then 
    sudo add-apt-repository -y ppa:juju/stable
    sudo apt-get update 
    sudo apt-get install -y -q amulet
fi

dpkg -s python-requests > /dev/null || sudo apt-get install -y -q python-requests
