#!/usr/bin/python
import setup
setup.pre_install()
import munin_utils
from charmhelpers.core import host, hookenv


@host.restart_on_change(munin_utils.RESTART_MAP)
def main():
    servers = munin_utils.get_munin_servers()
    hookenv.log("Servers related: %s" % ", ".join(servers),
                level=hookenv.DEBUG)
    munin_utils.render_conf(servers)


if __name__ == "__main__":
    main()
