#!/usr/bin/env python

import setup
setup.pre_install()
import munin_utils
from charmhelpers.core import hookenv, host


@host.restart_on_change(munin_utils.restart_map)
def main():
    servers = munin_utils.get_munin_servers()
    munin_utils.render_munin_node_conf(munin_servers)


if __name__ == "__main__":
    main()
